export type Counter = 'こ' | 'まい' | 'だい';

export type ItemDef = {
  name: string;      // ひらがな/カタカナの題材名
  counter: Counter;  // 助数詞
  edible: boolean;   // 食べられるか(「たべる」系テンプレートに使えるか)
};

export type WordTemplate = {
  id: string;                    // 一意なID 例 'add-01' 'sub-01'
  op: 'addition' | 'subtraction';
  requiresEdible: boolean;       // trueなら edible な題材のみ差し込む
  text: string;                  // プレースホルダ {item} {a} {b} {c} を含む文
};

export const ITEMS: ItemDef[] = [
  { name: 'いちご', counter: 'こ', edible: true },
  { name: 'みかん', counter: 'こ', edible: true },
  { name: 'あめ', counter: 'こ', edible: true },
  { name: 'たまご', counter: 'こ', edible: true },
  { name: 'ミニトマト', counter: 'こ', edible: true },
  { name: 'さくらんぼ', counter: 'こ', edible: true },
  { name: 'どんぐり', counter: 'こ', edible: false },
  { name: 'ふうせん', counter: 'こ', edible: false },
  { name: 'けしゴム', counter: 'こ', edible: false },
  { name: 'ボール', counter: 'こ', edible: false },
  { name: 'おはじき', counter: 'こ', edible: false },
  { name: 'ビーだま', counter: 'こ', edible: false },
  { name: 'クッキー', counter: 'まい', edible: true },
  { name: 'せんべい', counter: 'まい', edible: true },
  { name: 'シール', counter: 'まい', edible: false },
  { name: 'おりがみ', counter: 'まい', edible: false },
  { name: 'カード', counter: 'まい', edible: false },
  { name: 'きって', counter: 'まい', edible: false },
  { name: 'くるま', counter: 'だい', edible: false },
  { name: 'ミニカー', counter: 'だい', edible: false },
  { name: 'じてんしゃ', counter: 'だい', edible: false },
];

export const WORD_TEMPLATES: WordTemplate[] = [
  // ===== 足し算 (addition) =====
  { id: 'add-01', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} あります。そこへ {b} {c} ふえました。{item}は ぜんぶで なん{c} に なりましたか?' },
  { id: 'add-02', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} もって います。ともだちに {b} {c} もらいました。ぜんぶで なん{c} ですか?' },
  { id: 'add-03', op: 'addition', requiresEdible: false, text: 'かごに {item}が {a} {c} あります。あとから {b} {c} いれました。ぜんぶで なん{c} ですか?' },
  { id: 'add-04', op: 'addition', requiresEdible: false, text: 'はこの なかに {item}が {a} {c} あります。{b} {c} たしました。ぜんぶで なん{c} ですか?' },
  { id: 'add-05', op: 'addition', requiresEdible: false, text: 'こうえんに {item}が {a} {c} あります。あとから {b} {c} ふえました。ぜんぶで なん{c} ですか?' },
  { id: 'add-06', op: 'addition', requiresEdible: false, text: 'わたしは {item}を {a} {c} もって います。おかあさんから {b} {c} もらいました。あわせて なん{c} ですか?' },
  { id: 'add-07', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} ならんで います。そこへ {b} {c} やって きました。ぜんぶで なん{c} ですか?' },
  { id: 'add-08', op: 'addition', requiresEdible: false, text: 'あかい {item}が {a} {c} あります。あおい {item}が {b} {c} あります。あわせて なん{c} ですか?' },
  { id: 'add-09', op: 'addition', requiresEdible: false, text: 'みぎの てに {item}を {a} {c}、ひだりの てに {b} {c} もって います。あわせて なん{c} ですか?' },
  { id: 'add-10', op: 'addition', requiresEdible: false, text: 'つくえの うえに {item}が {a} {c} あります。ひきだしに {b} {c} あります。あわせて なん{c} ですか?' },
  { id: 'add-11', op: 'addition', requiresEdible: false, text: 'きのう {item}を {a} {c} かいました。きょう {b} {c} かいました。あわせて なん{c} ですか?' },
  { id: 'add-12', op: 'addition', requiresEdible: false, text: 'おにいさんが {item}を {a} {c}、いもうとが {b} {c} もって います。あわせて なん{c} ですか?' },
  { id: 'add-13', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} あります。おじいさんが {b} {c} くれました。ぜんぶで なん{c} ですか?' },
  { id: 'add-14', op: 'addition', requiresEdible: false, text: 'かびんに {item}が {a} {c} あります。もう ひとつの かびんに {b} {c} あります。あわせて なん{c} ですか?' },
  { id: 'add-15', op: 'addition', requiresEdible: false, text: 'あさ {item}を {a} {c} ひろいました。ゆうがた {b} {c} ひろいました。あわせて なん{c} ですか?' },
  { id: 'add-16', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} もって いました。おみせで {b} {c} かいました。ぜんぶで なん{c} ですか?' },
  { id: 'add-17', op: 'addition', requiresEdible: false, text: 'ふくろに {item}が {a} {c} はいって います。{b} {c} つけたしました。ぜんぶで なん{c} ですか?' },
  { id: 'add-18', op: 'addition', requiresEdible: false, text: 'いえに {item}が {a} {c} あります。おみやげで {b} {c} もらいました。ぜんぶで なん{c} ですか?' },
  { id: 'add-19', op: 'addition', requiresEdible: false, text: '{a} {c} の {item}に、あたらしく {b} {c} くわわりました。ぜんぶで なん{c} ですか?' },
  { id: 'add-20', op: 'addition', requiresEdible: false, text: 'たろうくんは {item}を {a} {c} もって います。はなこさんは {b} {c} もって います。あわせて なん{c} ですか?' },
  { id: 'add-21', op: 'addition', requiresEdible: false, text: 'きょうしつに {item}が {a} {c} あります。せんせいが {b} {c} もって きました。ぜんぶで なん{c} ですか?' },
  { id: 'add-22', op: 'addition', requiresEdible: false, text: 'おさらに {item}が {a} {c} あります。おかわりに {b} {c} のせました。ぜんぶで なん{c} ですか?' },
  { id: 'add-23', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} つくりました。あとで {b} {c} つくりました。あわせて なん{c} ですか?' },
  { id: 'add-24', op: 'addition', requiresEdible: false, text: 'はたけで {item}が {a} {c} とれました。となりの はたけで {b} {c} とれました。あわせて なん{c} ですか?' },
  { id: 'add-25', op: 'addition', requiresEdible: false, text: 'きのう {item}を {a} {c} あつめました。きょう {b} {c} あつめました。あわせて なん{c} ですか?' },
  { id: 'add-26', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} あります。そこに {b} {c} とんで きました。ぜんぶで なん{c} ですか?' },
  { id: 'add-27', op: 'addition', requiresEdible: false, text: 'おかしの はこに {item}が {a} {c} あります。{b} {c} もらって いれました。ぜんぶで なん{c} ですか?' },
  { id: 'add-28', op: 'addition', requiresEdible: false, text: 'うえの たなに {item}が {a} {c}、したの たなに {b} {c} あります。あわせて なん{c} ですか?' },
  { id: 'add-29', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} かって かえりました。いえに {b} {c} ありました。ぜんぶで なん{c} ですか?' },
  { id: 'add-30', op: 'addition', requiresEdible: false, text: 'こどもたちが {item}を {a} {c} もって きました。あとから {b} {c} ふえました。ぜんぶで なん{c} ですか?' },
  { id: 'add-31', op: 'addition', requiresEdible: false, text: 'かごの なかの {item}は {a} {c} です。{b} {c} いれると ぜんぶで なん{c} ですか?' },
  { id: 'add-32', op: 'addition', requiresEdible: false, text: 'あかちゃんが {item}を {a} {c} もって います。おねえさんが {b} {c} あげました。ぜんぶで なん{c} ですか?' },
  { id: 'add-33', op: 'addition', requiresEdible: false, text: 'まえに {item}が {a} {c} ならんで います。うしろに {b} {c} ならびました。あわせて なん{c} ですか?' },
  { id: 'add-34', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} あります。もう {b} {c} みつけました。ぜんぶで なん{c} ですか?' },
  { id: 'add-35', op: 'addition', requiresEdible: false, text: 'ポケットに {item}が {a} {c} あります。かばんに {b} {c} あります。あわせて なん{c} ですか?' },
  { id: 'add-36', op: 'addition', requiresEdible: false, text: 'きょう {item}を {a} {c} つくって、あした {b} {c} つくります。あわせて なん{c} ですか?' },
  { id: 'add-37', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} もって います。プレゼントで {b} {c} もらいました。ぜんぶで なん{c} ですか?' },
  { id: 'add-38', op: 'addition', requiresEdible: false, text: 'はこに {item}が {a} {c} はいって います。あとで {b} {c} たしました。ぜんぶで なん{c} ですか?' },
  { id: 'add-39', op: 'addition', requiresEdible: false, text: 'にわに {item}が {a} {c} あります。かぜで {b} {c} とんで きました。ぜんぶで なん{c} ですか?' },
  { id: 'add-40', op: 'addition', requiresEdible: false, text: 'あさ {item}が {a} {c} ありました。おひるに {b} {c} ふえました。ぜんぶで なん{c} ですか?' },
  { id: 'add-41', op: 'addition', requiresEdible: false, text: 'おみせに {item}が {a} {c} ならんで います。てんいんさんが {b} {c} ならべました。ぜんぶで なん{c} ですか?' },
  { id: 'add-42', op: 'addition', requiresEdible: false, text: 'わたしの {item}は {a} {c}、ともだちの {item}は {b} {c} です。あわせて なん{c} ですか?' },
  { id: 'add-43', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} かいました。おまけで {b} {c} もらいました。ぜんぶで なん{c} ですか?' },
  { id: 'add-44', op: 'addition', requiresEdible: false, text: 'かごに {item}が {a} {c} あります。あとから {b} {c} ころがって きました。ぜんぶで なん{c} ですか?' },
  { id: 'add-45', op: 'addition', requiresEdible: false, text: '{item}が {a} {c} あります。おともだちが {b} {c} くれました。ぜんぶで なん{c} に なりましたか?' },
  { id: 'add-46', op: 'addition', requiresEdible: false, text: 'きの うえに {item}が {a} {c} あります。したに {b} {c} おちて います。あわせて なん{c} ですか?' },
  { id: 'add-47', op: 'addition', requiresEdible: false, text: 'はじめに {item}が {a} {c} ありました。{b} {c} もらって ふえました。ぜんぶで なん{c} ですか?' },
  { id: 'add-48', op: 'addition', requiresEdible: false, text: '{item}を {a} {c} ならべました。あとで {b} {c} ならべました。あわせて なん{c} ですか?' },
  { id: 'add-49', op: 'addition', requiresEdible: false, text: 'こうえんに {item}が {a} {c} おちて います。もう {b} {c} みつけました。あわせて なん{c} ですか?' },
  { id: 'add-50', op: 'addition', requiresEdible: false, text: 'かぞくで {item}を {a} {c} あつめました。しんせきが {b} {c} くれました。ぜんぶで なん{c} ですか?' },

  // ===== 引き算 (subtraction) =====
  { id: 'sub-01', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。そのうち {b} {c} たべました。{item}は なん{c} のこって いますか?' },
  { id: 'sub-02', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。ともだちに {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-03', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} つかいました。のこりは なん{c} ですか?' },
  { id: 'sub-04', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。{b} {c} おとしました。のこりは なん{c} ですか?' },
  { id: 'sub-05', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。{b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-06', op: 'subtraction', requiresEdible: false, text: 'かごに {item}が {a} {c} あります。{b} {c} とりだしました。のこりは なん{c} ですか?' },
  { id: 'sub-07', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。ともだちに {b} {c} くばりました。のこりは なん{c} ですか?' },
  { id: 'sub-08', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} なくしました。のこりは なん{c} ですか?' },
  { id: 'sub-09', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって いました。おとうとに {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-10', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。かぜで {b} {c} とんで いきました。のこりは なん{c} ですか?' },
  { id: 'sub-11', op: 'subtraction', requiresEdible: true, text: 'おさらに {item}が {a} {c} あります。{b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-12', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} どこかへ いって しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-13', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} おともだちに わけました。のこりは なん{c} ですか?' },
  { id: 'sub-14', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。{b} {c} つかって しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-15', op: 'subtraction', requiresEdible: false, text: 'はこに {item}が {a} {c} あります。{b} {c} だしました。のこりは なん{c} ですか?' },
  { id: 'sub-16', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} ならんで います。{b} {c} うれました。のこりは なん{c} ですか?' },
  { id: 'sub-17', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。おやつに {b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-18', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} プレゼントしました。のこりは なん{c} ですか?' },
  { id: 'sub-19', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。いもうとに {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-20', op: 'subtraction', requiresEdible: false, text: 'こうえんに {item}が {a} {c} あります。{b} {c} もって かえりました。のこりは なん{c} ですか?' },
  { id: 'sub-21', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。{b} {c} たべました。あと なん{c} ありますか?' },
  { id: 'sub-22', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} かたづけて しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-23', op: 'subtraction', requiresEdible: false, text: 'かごの {item}が {a} {c} あります。{b} {c} とりました。のこりは なん{c} ですか?' },
  { id: 'sub-24', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。おみせで {b} {c} つかいました。のこりは なん{c} ですか?' },
  { id: 'sub-25', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。はんぶんこして {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-26', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。ゆうがたに {b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-27', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} どこかへ いって しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-28', op: 'subtraction', requiresEdible: false, text: 'ふくろに {item}が {a} {c} あります。{b} {c} とりだして つかいました。のこりは なん{c} ですか?' },
  { id: 'sub-29', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。おきゃくさんに {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-30', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。{b} {c} たべて しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-31', op: 'subtraction', requiresEdible: false, text: 'つくえに {item}が {a} {c} あります。{b} {c} かたづけました。のこりは なん{c} ですか?' },
  { id: 'sub-32', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。おともだちに {b} {c} かしました。のこりは なん{c} ですか?' },
  { id: 'sub-33', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。{b} {c} おとして なくしました。のこりは なん{c} ですか?' },
  { id: 'sub-34', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。あさごはんに {b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-35', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} おにいさんに あげました。のこりは なん{c} ですか?' },
  { id: 'sub-36', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} ならんで います。{b} {c} うれて いきました。のこりは なん{c} ですか?' },
  { id: 'sub-37', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} つかって へりました。のこりは なん{c} ですか?' },
  { id: 'sub-38', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。おやつの じかんに {b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-39', op: 'subtraction', requiresEdible: false, text: 'かごに {item}が {a} {c} あります。{b} {c} だして ともだちに あげました。のこりは なん{c} ですか?' },
  { id: 'sub-40', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} つかって なくなりました。のこりは なん{c} ですか?' },
  { id: 'sub-41', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。{b} {c} おともだちに くばりました。のこりは なん{c} ですか?' },
  { id: 'sub-42', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。{b} {c} たべたので へりました。のこりは なん{c} ですか?' },
  { id: 'sub-43', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} もって おでかけしました。のこりは なん{c} ですか?' },
  { id: 'sub-44', op: 'subtraction', requiresEdible: false, text: 'はこの {item}が {a} {c} あります。{b} {c} つかいました。あと なん{c} ですか?' },
  { id: 'sub-45', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。おとうさんに {b} {c} あげました。のこりは なん{c} ですか?' },
  { id: 'sub-46', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} ひとに あげて しまいました。のこりは なん{c} ですか?' },
  { id: 'sub-47', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。ばんごはんの あとに {b} {c} たべました。のこりは なん{c} ですか?' },
  { id: 'sub-48', op: 'subtraction', requiresEdible: false, text: '{item}を {a} {c} もって います。{b} {c} つかいきりました。のこりは なん{c} ですか?' },
  { id: 'sub-49', op: 'subtraction', requiresEdible: false, text: '{item}が {a} {c} あります。{b} {c} おちて なくなりました。のこりは なん{c} ですか?' },
  { id: 'sub-50', op: 'subtraction', requiresEdible: true, text: '{item}が {a} {c} あります。みんなで {b} {c} たべました。のこりは なん{c} ですか?' },
];
